"""Initial 2

Revision ID: 3507bfca0cb2
Revises: 918ffc17496b
Create Date: 2025-05-31 19:04:55.506952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3507bfca0cb2'
down_revision: Union[str, None] = '918ffc17496b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('type_of_bird', sa.String(), nullable=False))
    op.drop_column('birds', 'type_of_poultry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds', sa.Column('type_of_poultry', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('birds', 'type_of_bird')
    # ### end Alembic commands ###
