"""Initial 11

Revision ID: 50f85b27878a
Revises: eb0369e6fb55
Create Date: 2025-06-04 12:44:43.037521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50f85b27878a'
down_revision: Union[str, None] = 'eb0369e6fb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds_in_cells', sa.Column('cell_number', sa.Integer(), nullable=False))
    op.drop_constraint('birds_in_cells_cell_id_fkey', 'birds_in_cells', type_='foreignkey')
    op.create_foreign_key(None, 'birds_in_cells', 'cells', ['cell_number'], ['id'])
    op.drop_column('birds_in_cells', 'cell_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('birds_in_cells', sa.Column('cell_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'birds_in_cells', type_='foreignkey')
    op.create_foreign_key('birds_in_cells_cell_id_fkey', 'birds_in_cells', 'cells', ['cell_id'], ['id'])
    op.drop_column('birds_in_cells', 'cell_number')
    # ### end Alembic commands ###
