"""Initial 9

Revision ID: b5c199f8dee3
Revises: 00776b830d6c
Create Date: 2025-05-31 23:06:25.219624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c199f8dee3'
down_revision: Union[str, None] = '00776b830d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds_in_cells',
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('bird_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bird_id'], ['birds.id'], ),
    sa.ForeignKeyConstraint(['cell_id'], ['cells.id'], ),
    sa.PrimaryKeyConstraint('cell_id', 'bird_id')
    )
    op.drop_constraint('uq_cell_date', 'cells', type_='unique')
    op.drop_constraint('cells_bird_id_fkey', 'cells', type_='foreignkey')
    op.drop_column('cells', 'bird_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('bird_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cells_bird_id_fkey', 'cells', 'birds', ['bird_id'], ['id'])
    op.create_unique_constraint('uq_cell_date', 'cells', ['cell_number', 'date'])
    op.drop_table('birds_in_cells')
    # ### end Alembic commands ###
