"""Initial 6

Revision ID: b91782e92e61
Revises: 6c1c61f6651c
Create Date: 2025-05-31 22:38:10.312969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91782e92e61'
down_revision: Union[str, None] = '6c1c61f6651c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('bird_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cells', 'birds', ['bird_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cells', type_='foreignkey')
    op.drop_column('cells', 'bird_id')
    # ### end Alembic commands ###
