"""Initial 3

Revision ID: d4657db1176e
Revises: 3507bfca0cb2
Create Date: 2025-05-31 20:30:57.969681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4657db1176e'
down_revision: Union[str, None] = '3507bfca0cb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cells', sa.Column('cell_number', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('cells', sa.Column('bird_id', sa.Integer(), nullable=True))
    op.add_column('cells', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_cell_date', 'cells', ['cell_number', 'date'])
    op.create_foreign_key('fk_cells_bird_id', 'cells', 'birds', ['bird_id'], ['id'])
    op.create_foreign_key('fk_cells_worker_id', 'cells', 'workers', ['worker_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_cells_worker_id', 'cells', type_='foreignkey')
    op.drop_column('cells', 'worker_id')

    op.drop_constraint('fk_cells_bird_id', 'cells', type_='foreignkey')
    op.drop_column('cells', 'bird_id')

    op.drop_column('cells', 'cell_number')
    # ### end Alembic commands ###
